export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const GET_VALUE = "GET_VALUE";
export const LOADING_MEDICINCES = "LOADING_MEDICINCES";
export const ERROR_MEDICINCES = "ERROR_MEDICINCES";